### ISSUE TITLE
Falende stickey-pull-request-comment integration

### ISSUE THREAD

**Issue by floort** [MinBZK/Algoritmekader#79]
**Describe the bug**
It appears that pull request from people without commit access to this repo get a the following error on a github action that blocks the pull request:
`Run marocchino/sticky-pull-request-comment@331f8f5b4215f0445d3c07b4967662a32a2d3e31
Error: Resource not accessible by integration`

**To Reproduce**
1. As someone without commit acces: create a fork
2. Make some changes to the fork an submit a pull request
3. Observe the above error

**Expected behavior**
No error

**Screenshots**
![Screenshot 2024-04-04 at 14 18 28](https://github.com/MinBZK/Algoritmekader/assets/140608/52cc8439-2cca-4ce1-91c5-9513cb082828)

**Additional context**
Issue seems to be known by @berrydenhartog in a comment that is now removed from #72. Posting it here as a bug report as it's undocumented now.

**Comment by berrydenhartog** [comment]
@floort. This is indeed the case but is does not block the PR. The PR is only blocked by no approving reviews yet. 

The reason the action fails is because of this github action that tries to deploy a version of a PR to the website for review:
https://github.com/MinBZK/Algoritmekader/blob/1d4f56122d4727d31612b059cc11e837fd9be2cb/.github/workflows/preview.yaml#L44

This issue is described in the github action as a known problem. 
> This Action does not currently support deploying previews for PRs from forks, but will do so in https://github.com/rossjrw/pr-preview-action/pull/6.

We could solve it by not running the action for forked repos

**Comment by floort** [comment]
Good to hear that it's not a blocking issue.

P.S. I noticed I'm switching between English and Dutch. Here the bug report template is English so I stuck to that without thinking about it. What's the preferred language for contributions?

**Comment by ruthkoole** [comment]
Zowel Nederlands als Engels is goed om een issue te melden. Het algoritmekader is in het Nederlands, daarom lijkt Nederlands logischer. Maar de bugs zijn in het Engels, waardoor dat ook een logische keuze is.

Vervelend dat dit leidt tot een error.

@berrydenhartog kan jij kijken of we deze functionaliteit uit kunnen zetten voor forked repo's?

**Comment by berrydenhartog** [comment]
@ruthkoole. Ik zal de github action uitzetten voor forked repos
